### PR TITLE
Update tooling and protocols

### PR DESCRIPTION
**Pull request by georgiosd**

### CODE REVIEW

**Comment by georgiosd** [comment]
Not sure why the check is failing, compiles fine here.

**Comment by qmfrederik** [comment]
It looks like it's related to the .NET Core tooling. I'll try to have a look at it later this week - ping me if you do not hear back from me.

**Comment by georgiosd** [comment]
Weird, I didn't change anything to the project itself.

**Comment by georgiosd** [comment]
Some of these changes are breaking but useful. If you'd like to keep backwards-compatibility, you're welcome to modify them - obvious, I know :)

**Comment by qmfrederik** [comment]
@georgiosd There are some merge conflicts because the code which supports optional attributes has been merged.

Could you rebase this against master and update the PR? You'll also need to re-generate the classes since optional attributes will now be marked properly.

**Comment by georgiosd** [comment]
Sorry for the delay, will try to get to it this week

**Comment by georgiosd** [comment]
Guys, apologies but I no longer have a need for this and very little time right now.
You're welcome to merge the changes (as much or as little of) but unfortunately I can't spend more time on this right now...

**Comment by qmfrederik** [comment]
@georgiosd Thanks for the heads up! I'll probably have a look at this in the future, no promises though :)

**Pull request merged**
